"""add default values for Post and User model's feilds

Revision ID: 0000cbe3669f
Revises: a4f4211a9d56
Create Date: 2026-04-15 09:32:53.619111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0000cbe3669f'
down_revision: Union[str, Sequence[str], None] = 'a4f4211a9d56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'post_media_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'post_media_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
